version: "3.7"
services:
  app:
    build: ./app
    working_dir: /app
    command: [ "/bin/bash", "-c", "php -S 0.0.0.0:8000" ]
    volumes:
      - ./app:/app:cached
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:8000